### ISSUE TITLE
Get page followers

### ISSUE THREAD

**Issue by sneko** [austinoboyle/scrape-linkedin-selenium#100]
Hi @austinoboyle ,

Just curious, do you know a library to scrap profile URLs the followers of a specific group/page?

(no need of getting user information, just want their profile URLs)

Thank you,

**Comment by austinoboyle** [comment]
I'm not aware of a page on LinkedIn that lists this sort of data publicly. I've only seen pages' numbers of subscribers, not the subscribers themselves.
