### ISSUE TITLE
Running this package on an EC2 instance

### ISSUE THREAD

**Issue by dsc03** [austinoboyle/scrape-linkedin-selenium#19]
Hey there, 

Thanks for making this. Its been super helpful for me. I haven't actually tried this yet, but I've done some research and it seems it isn't very straight forward to run packages that use Selenium/non-headless Chrome Drivers on an EC2 instance. I was wondering if you have any experience with running your package on an aws EC2, or if you don't if you have any thoughts on how I could configure the EC2 instance to do so appropriately? 

Thanks again for putting your time into this.

**Comment by austinoboyle** [comment]
I actually have done this headlessly (not specifically EC2 but should be roughly the same), and it really is not as complicated as it may seem.  See #12
