### ISSUE TITLE
Referencing Scrape Linkedin in Requirements.txt

### ISSUE THREAD

**Issue by dsc03** [austinoboyle/scrape-linkedin-selenium#20]
Hey Austin,

One more question: in my remote server, I'm trying to add your repo to the requirements.txt file. I added 'scrape_linkedin==0.3.2' but the aws instance returns an error saying it can't find the package. I looked through the read me and realized you had the command:

`pip install git+git://github.com/austinoboyle/scrape-linkedin-selenium.git`

I don't think thats a valid string to add to my requirements.txt file, so I'm wondering how I can add this package?

**Comment by austinoboyle** [comment]
Adding `git+git://github.com/austinoboyle/scrape-linkedin-selenium.git` to your requirements.txt will work fine.  You can specify the version/tag to install with `git+git://github.com/austinoboyle/scrape-linkedin-selenium.git@tag_name`
