### ISSUE TITLE
Passing Parameters into Chrome Options

### ISSUE THREAD

**Issue by dsc03** [austinoboyle/scrape-linkedin-selenium#21]
Hey Austin,

So I've being trying to work with the CompanyScraper class, which I know inherits from Scraper class.

The Scraper class has a parameter called ```driver_options```, for which I'm trying input the following:

```
        chrome_options = se.webdriver.ChromeOptions()
        chrome_options.add_argument('--headless')
        chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument('--disable-dev-shm-usage')
  
        with CompanyScraper(driver_options=chrome_options) as scraper:
```

I'm getting the following error though:

```
<type 'exceptions.TypeError'>
type object argument after ** must be a mapping, not Options
```

It seems as if it doesn't like the Options object, and wants a key/value dictionary instead. Is this true? If so, what are the valid keys that this parameter can take?

Thanks again.

-Daniel

**Comment by iamprakashom** [comment]
Hi @dsc03, you can pass chrome options as below.

```
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')

with CompanyScraper(driver_options={"chrome_options":chrome_options}) as scraper:
   # scrap company page

```
It will open Chrome in minimized mode.
Hope it helps!
