### ISSUE TITLE
CompanyScraper

### ISSUE THREAD

**Issue by RockstarFinder** [austinoboyle/scrape-linkedin-selenium#25]
Hi, 
the CompanyScraper component to scrape companies its not working, all field are returned as none.

regards

**Comment by austinoboyle** [comment]
Thanks for letting me know.  Can you give me an example name of a company you are scraping?

**Comment by RockstarFinder** [comment]
I try many, for example:
https://www.linkedin.com/company/y-zag/about/
https://www.linkedin.com/company/miami-technology-group-inc/about/

I also have  2 question for you?
- i set my scraper to run on the server, but know linked-in say he don't recognized my API. do you know how to avoid that or is any way to run the driver to work on the client side? 
- are you able to work on freelancer task??

**Comment by austinoboyle** [comment]
Ahh LinkedIn changed their ui for companies.  I'll get on this.  As for the IP Blocking, I'm not sure how to handle this.  For freelance jobs, e-mail me at hello@austinoboyle.com and we can chat some more.
