### ISSUE TITLE
followers in profile information is not working

### ISSUE THREAD

**Issue by xxsacxx** [austinoboyle/scrape-linkedin-selenium#28]
I have tried with many public profile but for each of them followers is 'null', as : **_'followers': ''_**

Also can you please help me in setting the li_at cookie values in selenium driver ,while not using the profile_scraper

**Comment by austinoboyle** [comment]
Fixed in most recent version, thanks.  See https://github.com/austinoboyle/scrape-linkedin-selenium#config for setting LI_AT cookie.
