### ISSUE TITLE
Scrape user by e-mail

### ISSUE THREAD

**Issue by xxsacxx** [austinoboyle/scrape-linkedin-selenium#29]
By using :
**_url='https://www.linkedin.com/sales/gmail/profile/proxy/'+ gmail_**
we can reach directly to the profile of user without knowing his 'username'

**Comment by xxsacxx** [comment]
also in profile.py for me it is working with :
       

>  followers_text = text_or_default(soup_level1,
>                                          '.pv-recent-activity-section__follower-count', '').strip()
>         personal_info['followers'] = followers_text.split('\n')[0]

**Comment by austinoboyle** [comment]
I updated the profile scraper - a recent ui change caused the followers selector to fail.  It should work now.  I had no idea about that email feature, feel free to submit a pull request if you want to add that as a feature on the ProfileScraper

**Comment by xxsacxx** [comment]
Hi Austino, 
I found scrape-by-email has already been merged to the master.
Also if you could mention the same in readme.md ,it would be helpful for the community.

**Comment by xxsacxx** [comment]
Also as 'Selenium' is quite slow takes around (10secs/profile),have you tried with any other alternatives,
like pycurl etc

**Comment by austinoboyle** [comment]
Yes, this will not work AFAIK with anything other than a browser emulator.  LinkedIn has very strong anti-scraping measures, and will block requests from any suspicious source.  It is also almost completely javascript rendered, so you would need to manually make all AJAX calls manually, which would be quite cumbersome.

I will be sure to update the README to include the new feature documentation
