### ISSUE TITLE
Insights data from Company profiles

### ISSUE THREAD

**Issue by Kaan191** [austinoboyle/scrape-linkedin-selenium#30]
Hi Austin, 

Thanks for all the recent improvements, including dealing with the LinkedIn UI change for Companies. 

Before the UI change, I used to collect Insights data available (as a Premium user), by creating a new container ('summary-table') and updating the overview with information that showed you the % headcount change over 6 months, a year and 2 years. Very useful data. 

Now that the UI has changed, that information rests at linkedin.com/company/#name/insights... I'm far too useless at coding to begin to think how you would create a loop to create a new data structure to the very same company entry... I'm not sure if you have access to LinkedIn Premium insights but it would be interesting if you could take a look.

        table = one_or_default(
            self.overview_soup, 'table.org-insights-module__summary-table')

        overview.update(get_info(table, {
            '6m change': 'td:nth-of-type(2) span:nth-of-type(3)',
            '1y change': 'td:nth-of-type(3) span:nth-of-type(3)',
            '2y change': 'td:nth-of-type(4) span:nth-of-type(3)'

        }))

**Comment by austinoboyle** [comment]
I do not have premium so this would be a difficult thing for me to implement/test.  Here is what I think you would need to do.  Check the CompanyScraper code in the development branch. You will likely want to modify the scrape method to take a new parameter called 'insights' (default False), a new method called get_insights (in the same fashion as my other get_xyz methods).  Then you will add an insights parameter to the Company.py constructor.

If you get this working, I'd love a pull request.

**Comment by Kaan191** [comment]
Thanks Austin - I will have a play this week and share if I get it working. 

K

On 15 Dec 2018, at 14:21, austinoboyle <notifications@github.com> wrote:

I do not have premium so this would be a difficult thing for me to implement/test. Here is what I think you would need to do. Check the CompanyScraper code in the development branch. You will likely want to modify the scrape method to take a new parameter called 'insights' (default False), a new method called get_insights (in the same fashion as my other get_xyz methods). Then you will add an insights parameter to the Company.py constructor.

If you get this working, I'd love a pull request.

**Comment by Kaan191** [comment]
Hi - 
I have got this working and want to share the code but not sure how to do that via a pull request! (sorry complete newbie). I can email you the .py files as last resort.
K

**Comment by austinoboyle** [comment]
Awesome! I'll walk you through the Pull Request process, congrats on your very first!  I'll walk you through it:
1. If you have not done so, you need to 'fork' my repo (there is a button at the top of the project page)
2. Clone the forked repo locally on your computer
3. Edit the necessary files in this folder, commit them (with a message explaining your changes)
4. Push these changes to your forked repo
5. Click the 'pull requests' tab on my project page, and click the button to create a new one
6. Click the 'compare across forks' link, select 'development' as the base branch, and the branch you made the changes on as the compare branch.

All done!
