### ISSUE TITLE
Getting error while parsing HTML

### ISSUE THREAD

**Issue by nithinkashyapn** [austinoboyle/scrape-linkedin-selenium#31]
I am trying to parse an `HTML` file and i am getting the following error.

```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    print(profile.to_dict())
  File "/usr/local/lib/python2.7/dist-packages/scrape_linkedin/Profile.py", line 145, in to_dict
    info = super(Profile, self).to_dict()
  File "/usr/local/lib/python2.7/dist-packages/scrape_linkedin/ResultsObject.py", line 12, in to_dict
    vals = map(lambda attr: getattr(self, attr), self.attributes)
  File "/usr/local/lib/python2.7/dist-packages/scrape_linkedin/ResultsObject.py", line 12, in <lambda>
    vals = map(lambda attr: getattr(self, attr), self.attributes)
  File "/usr/local/lib/python2.7/dist-packages/scrape_linkedin/Profile.py", line 34, in personal_info
    style_string = image_div['style']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

My `main.py` looks like this

```
from scrape_linkedin import ProfileScraper, Profile

with open('nithin.html', 'r') as profile_file:
    profile = Profile(profile_file.read())
print(profile.to_dict())
```

Also, All the attributes like skills, education is empty :( 
And that's why the error is originating from `profile.to_dict()`.

Am i doing something wrong?

**Comment by austinoboyle** [comment]
Please attach the entire html file you are trying to parse, looks like the structure is different from the structure of the pages I was testing on

**Comment by nithinkashyapn** [comment]
Hey @austinoboyle ,

Sorry for the delay, was not in town.

PFA a copy of the `HTML` file i am using.

[nithin.html.zip](https://github.com/austinoboyle/scrape-linkedin-selenium/files/2711828/nithin.html.zip)

I am not able to parse the above.

**Comment by austinoboyle** [comment]
That's not a valid profile html file, that is LinkedIn's loading page that displays before loading the profile via AJAX calls.

**Comment by nithinkashyapn** [comment]
Can you please share a valid HTML page and how i can download the same?

**Comment by austinoboyle** [comment]
Any reason why you are not just using the regular scraper?  scrapeli --user USERNAME_TO_SCRAPE

**Comment by nithinkashyapn** [comment]
The regular scraper works like a charm it's great.

Thanks a lot for making it open source.

The need for a browser to scrape a profile is what my concern is; `Selenium` fires up a new window, logs in, visits a profile, scrolls through it and the window is closed.

This entire process takes a few seconds but in that time frame my team mates must need to key in a value or a character just so that a new request doesn't get assigned to them automatically and it's not feasible to pause and play so many times. Also, It is not possible for me to scrape a few profiles together in a batch.

So, was thinking to make a drag and drop box for them so that anyone can just drop a file and the `json` would populate. Time consumed would be kept minimal.

**Comment by austinoboyle** [comment]
The time to manually load and download the page html content is much higher than using the scraper to do everything for you, however if you would like to use it, in order to get a complete HTML page, you must:

1. Scroll down the linkedin profile page and open ALL expandable 'read more' type buttons
2. Open the 'Contact Info' modal
3. Inspect the page element (Ctrl, Shift, I, or right click->inspect element on Chrome)
4. Find and right click the 'body' tag, and find the option to copy outerHTML
5. Paste this into an html file

**Comment by nithinkashyapn** [comment]
Thank you.

Happy New Year!!
