### ISSUE TITLE
How to stop launching a 'new window' 

### ISSUE THREAD

**Issue by xxsacxx** [austinoboyle/scrape-linkedin-selenium#32]
Is there is a way by which launching of new window can be stopped (according to me it is an overhead).
isn't this should have been taken care by "scrape_linkedin.utils.HEADLESS_OPTIONS" passed to driver_options.

**Comment by austinoboyle** [comment]
Headless browsers still have to be launched, there is just no visible graphical component, so the overhead and memory usage is lower.  You may want to try scraping in parallel.  There is a section on this in the README
