### ISSUE TITLE
Scraping Profile pic URL

### ISSUE THREAD

**Issue by xxsacxx** [austinoboyle/scrape-linkedin-selenium#33]
Hi Austin,

profile picture is in **pv-top-card-section**:

<div aria-label="Sachin Tripathi" id="ember1418" class="pv-top-card-section__photo presence-entity__image EntityPhoto-circle-9 ember-view" style="background-image: url(&quot;https://media.licdn.com/dms/image/C5103AQGm11o0ehpU-w/profile-displayphoto-shrink_800_800/0?e=1551312000&amp;v=beta&amp;t=l4tqu7hDeEcFUP-hIgOhPbJOGL2TE6Nt7hg6tzHLYp0&quot;);">  <span class="visually-hidden">Sachin Tripathi</span>
</div>

**I tried this**(similar to the way we are hitting ''see contact info'' button) :     

```
    def get_profile_pic(self):
        try:
            self.driver.execute_script("window.scrollTo(0, 0);")
            button = self.driver.find_element_by_css_selector(
                '.pv-top-card-section__photo presence-entity__image')
            button.click()
            ppic=self.wait_for_el('.ember1688-modal-label')
            return ppic.get_attribute('outerHTML')
        except Exception as e:
            print(e)
            return ""

```
**Error :**
 Message: no such element: Unable to locate element: {"method":"css selector","selector":".pv-top-card-section__photo presence-entity__image"}

Approach : After hitting the pic , we can get the src of the image

**Comment by austinoboyle** [comment]
My script already gets profile images, it's under the 'image' field of personal_info.

**Comment by xxsacxx** [comment]
Thanks, I missed this update
