### ISSUE TITLE
Feed urls from a file

### ISSUE THREAD

**Issue by eiopago** [austinoboyle/scrape-linkedin-selenium#35]
It would be really useful to be able to feed urls from a text or csv file.

**Comment by austinoboyle** [comment]
This can be achieved with a pretty simple script.  Open the file in python, read the file line by line, run scraper on url on each line.
`
with open(YOUR_FILE, 'w') as f, ProfileScraper() as scraper:
    for username in f.readlines():
        results = scraper.scrape(username)
        #Do something with results, append to list, etc
`
