### ISSUE TITLE
Redirect error on large scrapes

### ISSUE THREAD

**Issue by tongxiaoting** [austinoboyle/scrape-linkedin-selenium#36]
Hi, Austin. Really need your help. I am still trapped with this problem after I deleted cookies and corrected the LI_AT  for several times. How can I deal with it?

**Comment by ernests** [comment]
I'm wondering how many times is "a lot of times" before LI_AT stops working.

**Comment by xxsacxx** [comment]
This is one issue I am facing since weeks, where even after correcting the LI_AT, scripts redirect to exception.
Currently workaround I am using is instead of just LI_AT , I am collecting all the cookies and adding it to the driver.
This has temporarily helped me.

**Comment by tongxiaoting** [comment]
> This is one issue I am facing since weeks, where even after correcting the LI_AT, scripts redirect to exception.
> Currently workaround I am using is instead of just LI_AT , I am collecting all the cookies and adding it to the driver.
> This has temporarily helped me.

Yes,I did the same work.

**Comment by austinoboyle** [comment]
@tongxiaoting Thanks for sharing the error sorry you're running into issues.  I have been unable to reproduce this.  Have you observed what happens in the browser when you receive the error?  How many times is "A Lot of Times"?
