### ISSUE TITLE
Need help. Companyscraper doesn't work and return error 

### ISSUE THREAD

**Issue by Cinmay2014** [austinoboyle/scrape-linkedin-selenium#37]
Hi Austin ,
I tried to run companyscraper but got error.
Traceback (most recent call last):
  File "C:/Users/xxx/PycharmProjects/lktest/111.py", line 5, in <module>
    print(company.to_dict())
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\scrape_linkedin\ResultsObject.py", line 13, in to_dict
    return dict(zip(self.attributes, vals))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\scrape_linkedin\ResultsObject.py", line 12, in <lambda>
    vals = map(lambda attr: getattr(self, attr), self.attributes)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\scrape_linkedin\Company.py", line 30, in overview
    overview['description'] = container.select_one(
AttributeError: 'NoneType' object has no attribute 'select_one'

Process finished with exit code 1

**Comment by Kaan191** [comment]
Because of a subtle LinkedIn UI change of the banner / top card of Company profiles. 

Try swapping the CSS Selector for the all_employees_links variable, from ‘.org-company-employees-snackbar__details-highlight’ to ‘.mt2’, in Company.py, line 45. Worked for me.

**Comment by Cinmay2014** [comment]
> Because of a subtle LinkedIn UI change of the banner / top card of Company profiles.
> 
> Try swapping the CSS Selector for the all_employees_links variable, from ‘.org-company-employees-snackbar__details-highlight’ to ‘.mt2’, in Company.py, line 45. Worked for me.

Thanks Kaan191, I tried, but still got error. Looks like a lot of things need to be changed.

**Comment by Cinmay2014** [comment]
I changed selector in company.py but still some wrongs here, anyone could correct them?
When I run the code, I got this result and no other infor I want, such as headquater, website
{'overview': {'name': None, 'num_employees': None, 'image': ''}, 'jobs': None, 'life': None}

CODE AS BELOW(JUST CHANGED SELECTOR):
from .utils import *
from .ResultsObject import ResultsObject
from bs4 import BeautifulSoup
import re


class Company(ResultsObject):
    """Linkedin User Profile Object"""

    attributes = ['overview', 'jobs', 'life']

    def __init__(self, overview, jobs="", life=""):
        self.overview_soup = BeautifulSoup(overview, 'html.parser')
        self.jobs_soup = BeautifulSoup(jobs, 'html.parser')
        self.life_soup = BeautifulSoup(life, 'html.parser')

    @property
    def overview(self):
        """Return dict of the overview section of the Linkedin Page"""

        # Banner containing company Name + Location
        banner = one_or_default(
            self.overview_soup, '#ember1017 > div')

        # Main container with company overview info
        container = one_or_default(
            self.overview_soup, '#org-about-company-module > div')

        overview = {}
        # select_one
        #overview['description'] = container.select_one('#ember112 > p').get_text().strip()

        metadata_keys = container.select('div.org-about-company-module__about-us-extra > div.org-about-company-module__about-us-extra-left-column> h3.org-about-company-module')
        metadata_values = container.select(
            'div.org-about-company-module__about-us-extra > div.org-about-company-module__about-us-extra-left-column> p.org-about-company-module')
        overview.update(
            get_info(banner, {'name': '#ember62 > h1'}))


        for key, val in zip(metadata_keys, metadata_values):
            dict_key = key.get_text().strip().lower().replace(" ", "_")
            dict_val = val.get_text().strip()
            overview[dict_key] = dict_val

        all_employees_links = all_or_default(
            banner, '#ember84 > strong')


        if all_employees_links:
            all_employees_text = all_employees_links[-1].text
        else:
            all_employees_text = ''

        match = re.search(r'((\d+?,?)+)', all_employees_text)
        if match:
            overview['num_employees'] = int(match.group(1).replace(',', ''))
        else:
            overview['num_employees'] = None

        logo_image_tag = one_or_default(
            banner, '#ember61 > div > img')
        overview['image'] = logo_image_tag['src'] if logo_image_tag else ''

        return overview

    @property
    def jobs(self):
        return None

    @property
    def life(self):
        return None

**Comment by austinoboyle** [comment]
What company are you trying to scrape? Are you using the most recent version of the scraper?  I have not been able to reproduce this

**Comment by austinoboyle** [comment]
I think I figured out the issue, looks like a UI change.  Update is on development branch, will be on master soon.
