### ISSUE TITLE
'chromedriver' executable needs to be in PATH

### ISSUE THREAD

**Issue by Daviddep** [austinoboyle/scrape-linkedin-selenium#39]
I am getting the following error: 
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

What do I need to do? I am rather new to programming.

**Comment by austinoboyle** [comment]
You need to add the directory your chrome driver is into your system's path.  On windows, this involves editing the PATH environment variable.  See https://www.java.com/en/download/help/path.xml

Also see https://stackoverflow.com/questions/29858752/error-message-chromedriver-executable-needs-to-be-available-in-the-path

**Comment by GihanMora** [comment]
sudo apt install chromium-chromedriver 
fixed my issue
