### ISSUE TITLE
issue with users with no groups

### ISSUE THREAD

**Issue by kouroshshafi** [austinoboyle/scrape-linkedin-selenium#40]
cannot scarpe user profile "rhys-parry" (https://www.linkedin.com/in/rhys-parry/)

error is a follows: 
rhys-parry could not be scraped
'NoneType' object has no attribute 'groups'

please fix this issue

**Comment by austinoboyle** [comment]
@kouroshshafi Scraping his profile worked fine for me just now. Can you post a full stacktrace?

**Comment by kouroshshafi** [comment]
When I am running parallel scrape process, I usually get:

darren-neubronner-a1897186 could not be scraped
'NoneType' object has no attribute 'lower'
lucy-omo-b7946 could not be scraped
'NoneType' object has no attribute 'groups'
xanneleo could not be scraped
'NoneType' object has no attribute 'groups'
kirankumartadaka could not be scraped
'NoneType' object has no attribute 'groups'
colleen-rees-b350b9156 could not be scraped
'NoneType' object has no attribute 'groups'
donald-juerno-68b63b15b could not be scraped
Profile Unavailable: Profile link does not match any current Linkedin Profiles
jigar-sojitra-9b6140b5 could not be scraped
'NoneType' object has no attribute 'groups'
konstantin-babaev-15bb202b could not be scraped
'NoneType' object has no attribute 'groups'
bismayanayak could not be scraped
'NoneType' object has no attribute 'groups'
sathiyansivaprakasam could not be scraped
Profile Unavailable: Profile link does not match any current Linkedin Profiles
vladimir-dubrovsky-73a332a could not be scraped
'NoneType' object has no attribute 'groups'
benjamin-li-8b65311a could not be scraped
'NoneType' object has no attribute 'groups'
dahye-song-b57a7a160 could not be scraped
'NoneType' object has no attribute 'groups'


----
The code certainly is working and I can clearly see the json getting the update; however, I am not sure what could cause that kind of error. For now I am re running the code a few times. It is still a strange issue.

**Comment by kouroshshafi** [comment]
Check this CSV file for inputs: https://www.dropbox.com/s/r9zl91ml5voqpl2/input_linkedin_links.csv?dl=0

Thanks again for looking into this issue. Again this is not an issue that breaks the code fully, but in some instances here and there throws this error.
