### ISSUE TITLE
KeyError: 'style'

### ISSUE THREAD

**Issue by NikitaNaychukov** [austinoboyle/scrape-linkedin-selenium#43]
This error started appearing recently. Tested for different profiles - every time it happened:

KeyError                                  Traceback (most recent call last)
<ipython-input-7-813b65ea078e> in <module>
      3 with ProfileScraper(cookie=MY_LI_AT) as scraper:
      4     profile = scraper.scrape(user='austinoboyle')
----> 5 print(profile.to_dict())

c:\users\minotebook\appdata\local\programs\python\python37-32\lib\site-packages\scrape_linkedin-0.5.4-py3.7.egg\scrape_linkedin\Profile.py in to_dict(self)
    145 
    146     def to_dict(self):
--> 147         info = super(Profile, self).to_dict()
    148         info['personal_info']['current_company_link'] = ''
    149         jobs = info['experiences']['jobs']

c:\users\minotebook\appdata\local\programs\python\python37-32\lib\site-packages\scrape_linkedin-0.5.4-py3.7.egg\scrape_linkedin\ResultsObject.py in to_dict(self)
     11         keys = self.attributes
     12         vals = map(lambda attr: getattr(self, attr), self.attributes)
---> 13         return dict(zip(self.attributes, vals))
     14 
     15     def __dict__(self):

c:\users\minotebook\appdata\local\programs\python\python37-32\lib\site-packages\scrape_linkedin-0.5.4-py3.7.egg\scrape_linkedin\ResultsObject.py in <lambda>(attr)
     10     def to_dict(self):
     11         keys = self.attributes
---> 12         vals = map(lambda attr: getattr(self, attr), self.attributes)
     13         return dict(zip(self.attributes, vals))
     14 

c:\users\minotebook\appdata\local\programs\python\python37-32\lib\site-packages\scrape_linkedin-0.5.4-py3.7.egg\scrape_linkedin\Profile.py in personal_info(self)
     32         else:
     33             image_div = one_or_default(top_card, '.pv-top-card-section__photo')
---> 34             style_string = image_div['style']
     35             pattern = re.compile('background-image: url\("(.*?)"')
     36             matches = pattern.match(style_string)

c:\users\minotebook\appdata\local\programs\python\python37-32\lib\site-packages\beautifulsoup4-4.7.1-py3.7.egg\bs4\element.py in __getitem__(self, key)
   1014         """tag[key] returns the value of the 'key' attribute for the tag,
   1015         and throws an exception if it's not there."""
-> 1016         return self.attrs[key]
   1017 
   1018     def __iter__(self):

KeyError: 'style'

**Comment by samanthad97** [comment]
I got the same issue, it appears to have something to do with trying to get the profile image of the person you are trying to scrape. For me, since I did not need the person's profile picture I just commented out the lines of code in Profile.py (lines 34-53 or so) where it tries to get the profile picture and everything else ran just fine after that! Hope this helps :)

**Comment by xXWingadiumXx** [comment]
It seems that style_string = image_div['src'] gives the image url instead of image_dic['style']

A temporary solution would be just do:
image_url = image_div['src']
and comment out the regex matching code below. It seems to be able to download the profile pic that way
