### ISSUE TITLE
UI Update - Several Breaking Changes

### ISSUE THREAD

**Issue by austinoboyle** [austinoboyle/scrape-linkedin-selenium#45]
There were several breaking changes in recent LinkedIn UI Updates.  Some of these are referenced in the following issues: #38 #41 #42 #43 

Sorry for being MIA for a while, I was on vacation without my laptop for all of May.  I will get working on fixing all of these soon.

**Comment by Becarefullu** [comment]
thx bro, hope you can fix this soon!
