### ISSUE TITLE
Company Scraper/Parser

### ISSUE THREAD

**Issue by austinoboyle** [austinoboyle/scrape-linkedin-selenium#5]
Allow users to scrape company info

**Comment by Stikemanley** [comment]
Hello,

Is there any progress on this as this would be incredibly useful

Thanks,
mike

**Comment by austinoboyle** [comment]
@Stikemanley Haven't been able to get to this yet.  What info from companies would you like to see in a scrape?

**Comment by Stikemanley** [comment]
Hey Austin,

I'm looking for these fields

--Company Name
--Industry
--City
--State
--Company Type
--Description
--Website
--Specialties (these are the key words)
--# of employees on LinkedIn

Thanks
