### ISSUE TITLE
Cannot get the scraped file

### ISSUE THREAD

**Issue by ChunyangHan996** [austinoboyle/scrape-linkedin-selenium#50]
Hi, 
I came across the following problem.
DevTools listening on ws://127.0.0.1:53412/devtools/browser/efb7d847-d8d3-48b8-8a0d-561a903746b3
Unable to determine current company...continuing

Here is the code:
i = 0
User_url = ['david-bain-jd-mba-536213116']
for user in User_url:       
        with ProfileScraper(cookie = 'AQEDAS1XPisBU5xgAAABbQEFRv0AAAFtJRHK_VYAx8bHyQ9Zg3zcaPVc7yXVFa0Tf6tnOvxb0W09x4LdMfHqHmaKAETfJ_6PmePuUzbXeo9BW7kuCcM2oBvAlTI7oNM_XahGFmX7bgVEE9dEvSMVjQHM') as scraper:

                time.sleep(randint(1,10))
                profile = scraper.scrape(user = user)
                

                # experience: jobs and education
                profile_dict = profile.to_dict()
                linkedin_dict = profile_dict['experiences']
                # personal info: About: summary 
                personal_dict = profile_dict['personal_info']
                About_str =  personal_dict['summary']

                # change items' name in case of repetition
                for d in linkedin_dict['jobs']:
                        d['company date_range'] = d.pop('date_range')
                
                for d in linkedin_dict['education']:
                        d['Education school'] = d.pop('name')
                        d['school date_range'] = d.pop('date_range')
                        d['school activities'] = d.pop('activities')
                
                #add the broker's name and profile url
                user_name = ''.join(filter(str.isalpha, user))
                linkedin_name = [{'Profile name': user_name , 'URL':'https://www.linkedin.com/in/' + user} ]                 
                for item in linkedin_name:
                        item.update({"summary":About_str}) 

                # dataframe for education, profile name, job 
                cols_edu = ['Education school','degree','school date_range','school activities','field_of_study','grades']
                df_edu = pd.DataFrame(linkedin_dict['education'])
                try:
                        df_edu = df_edu[cols_edu]
                except:
                        df_edu = df_edu

                cols_name = ['Profile name','URL','summary']
                df_name = pd.DataFrame(linkedin_name)
                try:
                        df_name = df_name[cols_name]
                except:
                        df_name = df_name 

                cols_job = ['title', 'company','company date_range','location','description','li_company_url']
                df_job = pd.DataFrame(linkedin_dict['jobs'])
                try:
                        df_job = df_job[cols_job]
                except:
                        df_job = df_job  

                #combine profile name, summary, education, job dataframes together to one dataframe
                df_proflie = pd.concat([df_name, df_edu, df_job], axis=1)

                if i == 0:
                        df = df_proflie 
                else:
                        df = pd.concat([df, df_proflie])
        
                i = i+1

df.to_excel('14.xlsx', index=False)

**Comment by ChunyangHan996** [comment]
when I run the code, I just got the error ''Unable to determine current company...continuing '', then i cannot get the result in the excel file. Could help me with this question ? Thank you very much.

**Comment by austinoboyle** [comment]
@ChunyangHan996 I was getting a different error than you when I tried scraping that profile.  My most recent commit/version should fix that issue.  There was a bug with handling multiple positions in a row at the same company.  If your issue continues after updating to the newest version, let me know and I will look into it.
