### ISSUE TITLE
ValueError: Took too long to load profile.

### ISSUE THREAD

**Issue by rajkotraja** [austinoboyle/scrape-linkedin-selenium#51]
saying ValueError: Took too long to load profile.
and chrome showing too many redirects. can you help how to fix

**Comment by austinoboyle** [comment]
@rajkotraja Sorry for the delayed response.  Are you still experiencing this? Have you properly set your LI_AT environment variable?  I've experienced Chrome redirecting indefinitely when my LI_AT is invalid.
