### ISSUE TITLE
No Module Named "scrape_linkedin"

### ISSUE THREAD

**Issue by samanthad97** [austinoboyle/scrape-linkedin-selenium#52]
Hi! I am trying to run the parallel scraper but keep getting the error message "no module named scrape_linkedin" which is strange because I did not alter any of the module or folder names. Any advice? For reference here is a screen shot of the code and error message that I received: 

![image](https://user-images.githubusercontent.com/49205262/65634790-da781480-df93-11e9-84d1-ae1b277427c2.png)

**Comment by austinoboyle** [comment]
In order to import from scrape_linkedin, you need to install the python package locally.  See https://github.com/austinoboyle/scrape-linkedin-selenium#installation
