### ISSUE TITLE
"unknown error: $ is not defined" with 'document.querySelectorAll'

### ISSUE THREAD

**Issue by lmartinezruizit** [austinoboyle/scrape-linkedin-selenium#56]
This change not fix the error.
![image](https://user-images.githubusercontent.com/25184023/66991234-f1f47a00-f0c7-11e9-85c2-580da3077e59.png)

_Originally posted by @lmartinezruizit in https://github.com/austinoboyle/scrape-linkedin-selenium/issues/53#issuecomment-543063900_

**Comment by austinoboyle** [comment]
This confuses me, as '$' doesn't appear in the javascript call being made.  Can you run a clean install of the package (ideally in a new virtual environment), and tell me if this issue persists?

**Comment by austinoboyle** [comment]
Closing issue as stale.  Feel free to re-open if this is still a problem.
