### ISSUE TITLE
Write the data to csv

### ISSUE THREAD

**Issue by roroar** [austinoboyle/scrape-linkedin-selenium#57]
Can we store the data to CSV format?

Thanks

**Comment by austinoboyle** [comment]
The full data tree is deeply nested and does not make sense to output as a csv.  If there are specific fields you would like in csv format then you can certainly achieve that.  I would suggest using the scrape_linkedin package in a custom python script, and accessing the attributes of the Profile object that you need: https://github.com/austinoboyle/scrape-linkedin-selenium#profiles

This will get you the data in a dict.  You can then use something like the [csv](https://docs.python.org/3/library/csv.html) or [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html) to convert the data to csv format.
