### ISSUE TITLE
I get "Error: Must set LI_AT environment variable"

### ISSUE THREAD

**Issue by mcmuralishclint** [austinoboyle/scrape-linkedin-selenium#58]
I try to run the code **scrapeli --user=austinoboyle** and I get this error but I've already run the code to set the LI_AT value. What am I missing?

**Comment by austinoboyle** [comment]
How are you setting the LI_AT variable? You need to set it in the same shell session as where you run the command.  You can either use `export LI_AT=...` and then run the command from the same shell instance, or `LI_AT=asdfasdf scrapeli --user=austinoboyle`

**Comment by mcmuralishclint** [comment]
Thanks. My bad, I wasn't setting it in the same shell.
