### ISSUE TITLE
Error: Must set LI_AT environment variable

### ISSUE THREAD

**Issue by javicarmona** [austinoboyle/scrape-linkedin-selenium#60]
Hi, 

I'm trying to set the LI_AT but i can't do it... what i'm doing is add the line: 
with ProfileScraper(cookie='xxxx') as scraper
to the scraper.py file... at the start of the file... is ok? 

Thank you!!

**Comment by jmrenouard** [comment]
Look at README.md

Find in your browser, value for cookie li_at 
set LI_AT=XXXX
export LI_AT=XXXX

**Comment by rithiksachdev** [comment]
That is not working for me. I am using a Windows 10 OS and Chrome. Also in the readme.md for windows, there is a $ prompt which is not the case in windows.

**Comment by austinoboyle** [comment]
I updated the README.  The '$' is something that displays in typical unix shells, but now Windows.  It is not a character you type, it is just there to show that this is a terminal command.

On windows, you open command prompt, and run `set LI_AT=YOUR_LI_AT`, or apparently, some people needed to run `setx LI_AT=...`

**Comment by rithiksachdev** [comment]
Sure, @austinoboyle thanks for the update. It worked for me after a couple of fixes.
