### ISSUE TITLE
How to scrape by email?

### ISSUE THREAD

**Issue by soliverc** [austinoboyle/scrape-linkedin-selenium#62]
I noticed in the Profilescraper.py file there's an email scraper:

```python
    def scrape_by_email(self, email):
        self.load_profile_page(
            'https://www.linkedin.com/sales/gmail/profile/proxy/{}'.format(email))
        return self.get_profile()
```
Not entirely sure how this works but I tried:
```python
profile = scraper.scrape(email='my_email@gmail.com')
print(profile.to_dict())

TypeError: scrape() got an unexpected keyword argument 'email'
```
So how exactly can we do this?

**Comment by austinoboyle** [comment]
The error is because you are calling `scraper.scrape(...)` instead of `scraper.scrape_by_email(...)`

Unfortunately, it looks like Linkedin no longer supports this email proxy feature that I took advantage of to do this, so it likely won't work anyways.
