### ISSUE TITLE
Profile Scraper stopped working (Company Scraper is OK) - Change in LinkedIn HTML?

### ISSUE THREAD

**Issue by Kaan191** [austinoboyle/scrape-linkedin-selenium#63]
Hi Austin,

I'd be curious if you - or any one else - has also experienced a recent issue with the scraper. I am using the Profile Scraper. It is still able to take as input a profile url and load the desired page. The Chrome browser changes dimensions like it usually does. But when the Profile page has loaded, the browser doesn't scroll to the bottom, and after a bit of a timeout, it throws the timeout error:

ACwAAAHQuGgBS0I8UhYd-YUcZ3YKstTxEstbLHk could not be scraped
Took too long to load profile.  Common problems/solutions:
                1. Invalid LI_AT value: ensure that yours is correct (they
                   update frequently)
                2. Slow Internet: increase the timeout parameter in the Scraper constructor

I suspect the Scraper isn't ingesting the Page's HTML correctly. I'll spend a bit of time investigating (don't have much time this week). The scraper was working perfectly a week ago and I haven't amended anything. Perhaps something weird has happened on my end, but it would be good to know if others are experiencing the same thing.

Company Scraper still worked for me as of this moment... bizarre.

Kaan

**Comment by austinoboyle** [comment]
I think this may have been fixed by #70 , feel free to re-open if that's not the case.
