### ISSUE TITLE
The chromedriver's path could not be found

### ISSUE THREAD

**Issue by deepsidh9** [austinoboyle/scrape-linkedin-selenium#65]
I installed as per the instructions given. But when i run it, it says " 'chromedriver' executable needs to be in PATH."

Do we need to explicitly give the path of the chromedriver somewhere as an argument?

**Comment by paras55** [comment]
Yes , you need to download the chromedriver to your working directory and then run the same . It works perfect .

**Comment by austinoboyle** [comment]
PATH is an environment variable on your computer. Look up "edit PATH on (Windows/Mac/Linux)" to see how to do it.  You want to add a new entry to the path for where chromedriver is installed
