### ISSUE TITLE
personal information is blank

### ISSUE THREAD

**Issue by leandr0** [austinoboyle/scrape-linkedin-selenium#69]
Dear all,
I'm performing some scrapes on linkedin profiles, however all the attributes inside personal_info is null.
Please find the JSON returned in a real case: 
{"personal_info": {"name": null, "headline": null, "company": null, "school": null, "location": null, "summary": "Food registers on Agriculture Ministry, Food and Beverages labelling, Food and Beverages Import and Export, Food quality system, food regulatory affairs, International relations, Foreign Trade expert, exporting to Brazil, Sanitary and Phytosanitary Expert, conflict solver, strategic planning, coordination on quality system and regulatory affairs, audits in food industry, experience in McDonald\u00b4s Quality System. Strategies in companies for resource saving and achieve maximum results. Management of the entire production chain. Experience in the implementation of industries self-control programs, development of quality programs ( HACCP, GMP, traceability ). Label development according Brazilian laws. Establishments and food products registers. Facilitator of workshops for HACCP, GMP, Traceability, labelling food, inspection, halal precepts, time management. (11)96450-0234vanessa@registroin.com.br", "image": "", "followers": "2,172", "email": "vanessa@registroin.com.br", "phone": "+55 11 964500234\n (Mobile)", "connected": "March 13, 2019", "websites": ["http://www.registroin.com.br"], "current_company_link": "https://www.linkedin.com//company/registro-in/"}, "experiences": {"jobs": [{"title": "Technical Director", "date_range": "Jan 2017 \u2013 Present", "location": "S\u00e3o Paulo Area, Brazil", "description": "Food registers on Agriculture Ministry, Food and Beverages labelling, Food and Beverages Import and Export, Food quality system, food regulatory affairs, International relations, Foreign Trade expert, exporting to Brazil, Sanitary and Phytosanitary Expert, conflict solver, strategic planning, coordination on quality system and regulatory affairs, audits in food industry, experience in McDonald\u00b4s Quality System. Strategies in companies for resource saving and achieve maximum results. Management of the entire production chain. Experience in the implementation of industries self-control programs, development of quality programs ( HACCP, GMP, traceability ). Label development according Brazilian laws. Establishments and food products registers. Facilitator of workshops for HACCP, GMP, Traceability, labelling food, inspection, halal precepts, time management. (11)96450-0234vanessa@registroin.com.br\n\n    \n\u2026\n\n        see more", "company": "Registro In", "li_company_url": "https://www.linkedin.com//company/registro-in/"}, {"title": "Technical Director", "date_range": "May 2017 \u2013 Present", "location": "S\u00e3o Paulo Area, Brazil", "description": "Consulting company focused on DIPOA / MAPA, imported food registries and labeling, adequacy to Brazilian legislation - ANVISA / DIPOA / MAPA.www.registroin.com.br", "company": "Registro In", "li_company_url": "https://www.linkedin.com//company/registro-in/"}, {"title": "Regulatory Affairs", "company": "TERRA NOVA TRADING", "date_range": "Mar 2019 \u2013 Present", "location": "S\u00e3o Paulo Area, Brazil", "description": "Responsible for Regulatory affairs at Terra Nova Trading", "li_company_url": "https://www.linkedin.com/company/terranovatrading/"}, {"title": "Project Expert", "company": "ALADI", "date_range": "Aug 2018", "location": "Brazil", "description": "Project about environmental measures in countries EXTRA ALADI and the relevance for Brazilian exportation", "li_company_url": "https://www.linkedin.com/company/aladi/"}, {"title": "SPS Expert", "company": "Elan Biz - European and Latin American Business Services", "date_range": "May 2016 \u2013 Jul 2018", "location": "S\u00e3o Paulo Area, Brazil", "description": "Sanitary and Phytosanitary Expert, in a European Union project platform, with updated information on sanitary and phytosanitary legislation, as well as market information, to promote trade between European Union and Latin American countries.- Doing business in Brazil.- Brazilian market access.- Local business environment.- Helping European entrepreneurs doing business in Brazil.- Solving doubts about Brazilian legislation.- Supports with tailored information European companies interested in investing or exporting in Latin America.- Supply comprehensive and continuously updated web-based information and analysis for better European SMEs\u2019 market penetration and for facilitating EU companies doing business in Latin American markets.- Answer tailored questions about Brazilian market or import requisits.- Provide up to date and comprehensive information related to SPS - Sanitary and Phytosanitary - issues in Brazil which apply to EU SMEs companies and of interest for EU stakeholders.- Improve provision of business support services to European SMEs and their intermediaries in general and with a special focus on specific sectors identified to have high growth potential and be of strategic interest for EU SMEs. - Re-enforce existing local EU business service provider.\n\n    \n\u2026\n\n        see more", "li_company_url": ""}, {"title": "Consultora Senior", "company": "Sob Controle Consultoria em Alimentos", "date_range": "Sep 2014 \u2013 May 2016", "location": "S\u00e3o Paulo", "description": "- System Developments - Self Programs, GMP, HACCP, Quality Manuals.- Development of food and drinks labels according brasilian laws. - Registration of Stablishments and products on Agriculture Ministry.- Regulatory Issues related to ANVISA, MAPA and INMETRO.- Evaluation of formulas of different kinds of products and adaptation of product and label in accordance with current regulations (MAPA, ANVISA, INMETRO).- Guidance and advice to meet the legal requirements required to qualify establishments for the food export;- Development of Self-Control Programs, adapting them to the legislation of several Countries;- Guidelines for the registration of establishments and products for import and export;- Advice and guidance for the elaboration and implementation of Self-Control Programs in food industries;- Training for Quality Teams in Self-Control Programs.\n\n    \n\u2026\n\n        see more", "li_company_url": ""}, {"title": "Coordenador de Qualidade", "company": "JBS SA", "date_range": "Jan 2012 \u2013 Aug 2014", "location": "Campo Grande - MS", "description": "- McDonald's Quality System Program implantation;- Management team of quality workers;- Process development that led to the approval of the establishment as a supplier of McDonald's hamburgers;- Establishment of quality standards, with the classification among suppliers as first or second, in the evaluation cuttings.- Reduction of waste products, - FIFO control during the storage process;- Implementation of quality control at all stages, with reduced product rework, and increased profit margins on products.- Development of documents and quality plans - HACCP / GMP, preparation for audits and supervision, process improvements, product analysis and its adaptation to current legislation.- Development and implementation of training in HACCP, GMP, traceability, labeling, time management.\n\n    \n\u2026\n\n        see more", "li_company_url": "https://www.linkedin.com/company/jbs/"}, {"title": "Consultora de Alimentos Senior", "company": "FoodStaff Assessoria de Alimentos Ltda", "date_range": "Sep 2010 \u2013 Sep 2011", "location": "S\u00e3o Paulo - SP", "description": "- Regulatory affairs consultant - ANVISA, MAPA and INMETRO.- Evaluation of national and imported ingredients products, and suitability to national legislations.- Labels development in accordance with current legislation.- Establishments and products registrations at Agriculture Ministry.- Registration of Imported Products (food and beverages).- Adaptation of different products formulations to Brazilian legislation in order to allow the product import.\n\n    \n\u2026\n\n        see more", "li_company_url": "https://www.linkedin.com/company/foodstaff-assessoria-de-alimentos-ltda/"}, {"title": "Analista de Qualidade e Exporta\u00e7\u00e3o", "company": "Braslo", "date_range": "2006 \u2013 Sep 2010", "location": "Osasco - SP", "description": "- Maximization of results and transport costs to  Middle East export , by optimizing the capacity of the container and change the size of product boxes - increased loaded volum over 14% per container.- Opening of export markets - Pakistan, Saudi Arabia, United Arab Emirates, Kuwait.- Importing / Exporting procedures.- Experience in McDonald's quality system.- HACCP, GMP and \"Compliance to Specification\".- Development and implementation of training in HACCP, GMP, Halal traceability and Halal precepts.- Act with clients abroad to ensure their satisfaction. Management of the entire production chain, including programming (PCP), production, storage and logistics.- Implementation of Halal precepts in production for Middle East export.- Studies of variation of raw material (sex and condition of animals), and the conditions of the freezing tunnel to maximize products shelf life, ensuring adequate quality and sensory evaluation after 45 days transit time, thus solving the problem of the gray line on burgers in the export process.- Studies ideal loading and maintenance of thermographic temperature monitoring the product to its reception in the Middle East temperature.\n\n    \n\u2026\n\n        see more", "li_company_url": "https://www.linkedin.com/company/braslo/"}, {"title": "Agente de Inspe\u00e7\u00e3o de Produtos de Origem Animal", "company": "Ministerio da Agricultura", "date_range": "2004 \u2013 2006", "location": null, "description": "- Analysis of establishments process and registrations on MAPA.- Analysis of products registrations on MAPA.- Analysis of establishments registrations on MAPA.-Fish establishments inspection.", "li_company_url": "https://www.linkedin.com/company/ministerio-da-agricultura/"}], "education": [{"name": "Universidade de S\u00e3o Paulo", "degree": null, "grades": null, "field_of_study": "Medicina Veterinaria", "date_range": "2001 \u2013 2005", "activities": "\u00canfase em Inspe\u00e7\u00e3o de Alimentos de Origem Animal"}, {"name": "APCE", "degree": "LEADER AUDITOR", "grades": "Leader Auditor - FSSC 22000", "field_of_study": "International Leader Auditor - FSSC 22000", "date_range": "2019 \u2013 2019", "activities": null}, {"name": "FGV - Funda\u00e7\u00e3o Getulio Vargas", "degree": "Master of Business Administration (MBA)", "grades": null, "field_of_study": "International Relations and Affairs", "date_range": "2017 \u2013 2018", "activities": null}, {"name": "International Coach Institute", "degree": "Professional Coach, Life Coach, Coach Sistemico", "grades": null, "field_of_study": null, "date_range": "2014 \u2013 2014", "activities": null}, {"name": "Instituto Voc\u00ea", "degree": null, "grades": "Practitioner", "field_of_study": "PNL", "date_range": "2013 \u2013 2013", "activities": null}, {"name": "Universidade de S\u00e3o Paulo", "degree": null, "grades": null, "field_of_study": "Veterinary Medicine", "date_range": "2001 \u2013 2005", "activities": null}, {"name": "Universidade de S\u00e3o Paulo", "degree": null, "grades": null, "field_of_study": "Veterinary Medicine", "date_range": "2001 \u2013 2005", "activities": null}], "volunteering": []}, "skills": [{"name": "Food Industry", "endorsements": "23"}, {"name": "Food Safety", "endorsements": "19"}, {"name": "Food Science", "endorsements": "14"}, {"name": "Food", "endorsements": "12"}, {"name": "ISO", "endorsements": "11"}, {"name": "Meat", "endorsements": "10"}, {"name": "Quality System", "endorsements": "8"}, {"name": "Ingredients", "endorsements": "8"}, {"name": "Food Registering", "endorsements": "4"}, {"name": "Food Labelling", "endorsements": "4"}, {"name": "Supply Chain", "endorsements": "3"}, {"name": "Process Management", "endorsements": "2"}, {"name": "Supply Chain Management", "endorsements": "2"}, {"name": "ISO Standards", "endorsements": "2"}, {"name": "Hazard Analysis and Critical Control Points (HACCP)\n          \n\n\n          Hazard Analysis and Critical Control Points (HACCP)", "endorsements": "2"}, {"name": "Coaching", "endorsements": "2"}, {"name": "BPF", "endorsements": "2"}, {"name": "Quality", "endorsements": "2"}, {"name": "Haccp", "endorsements": "1"}, {"name": "Process Improvement", "endorsements": "1"}, {"name": "Gest\u00e3o", "endorsements": "1"}, {"name": "Gest\u00e3o de projetos", "endorsements": "1"}, {"name": "Gest\u00e3o de tempo", "endorsements": "1"}, {"name": "Lideran\u00e7a de equipe", "endorsements": "1"}, {"name": "Lideran\u00e7a de equipe multifuncional\n          \n\n\n          Lideran\u00e7a de equipe multifuncional", "endorsements": "1"}], "accomplishments": {"publications": [], "certifications": [], "patents": [], "courses": [], "projects": ["ELANBiz"], "honors": [], "test_scores": [], "languages": ["English", "French", "Portuguese", "Spanish"], "organizations": []}, "interests": ["Mondel\u0113z International", "Sustainable Agriculture", "ELAN Biz", "Jeff Immelt", "Ricardo Amorim", "Empresas Espa\u00f1olas en Brasil"]}

**Comment by austinoboyle** [comment]
Fixed by #70
