### ISSUE TITLE
LI_AT Instruction

### ISSUE THREAD

**Issue by japoeder** [austinoboyle/scrape-linkedin-selenium#7]
I'm a bit unsure how to set the LI_AT variable and where to obtain the cookie information as this aspect of Python is a little new to me.  Can you provide some basic steps on how to obtain the cookie value that needs to be identified and how to set the variable please?

Thanks so much,
Jonathan

**Comment by austinoboyle** [comment]
I'll add these to the README in my next update, here are the instructions:

## Retrieving Cookie

**Browser-Independent:**
1. Navigate to Linkedin.com and log in
2. Open up the browser developer tools (Ctrl-Shift-I or right click -> inspect element)

**Chrome:**
1. Select the **Application** tab
3. Under the **Storage** header on the left-hand menu, click the **Cookies** dropdown and select `www.linkedin.com`
4. Find the li_at cookie, and double click the value to select it before copying

**Firefox:**
1. Select **Storage** tab
2. Click the **Cookies** dropdown and select `www.linkedin.com`
3. Find and copy the **li_at** value

## Setting LI_AT environment variable
**Mac/Linux:**
```bash
$ export LI_AT=your_li_at_value
```

**Windows:**
```bash
$ set LI_AT=your_li_at_value
```

**Comment by tongxiaoting** [comment]
I tried what you suggested in win10,but it still didn't work.

**Comment by austinoboyle** [comment]
What is your error?

**Comment by tongxiaoting** [comment]
> @tongxiaoting What is your error?
Thanks for your concern. It had been solved by changing 'set' into 'setx' , for it may be a little different in win10.

**Comment by austinoboyle** [comment]
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setx

**Comment by qiqi1231** [comment]
> I tried what you suggested in win10,but it still didn't work.

Hi, I have similar problem in win10, and I also tried setx, but it still doesn't work. 
My error is "ValueError: Must either define LI_AT environment variable, or pass a cookie string to the Scraper", but I indeed set the value. 

Can you help? Thank you.

**Comment by reemelmahdi** [comment]
I solved this problem by finding the LI_AT variable out of Chrome browser using @austinoboyle answer and assign the LI_AT variable manually at the Python script using:
`
os.environ['LI_AT'] = 'your_LI_AT'
`
