### ISSUE TITLE
cannot run on a VM (google cloud and EC2 instance)

### ISSUE THREAD

**Issue by paras55** [austinoboyle/scrape-linkedin-selenium#74]
I tried running on EC2 instance but it didn't worked . I referred to Issue 12 (https://github.com/austinoboyle/scrape-linkedin-selenium/issues/12) . But it didn't worked . 

please provide a way to run this script on server .

**Comment by austinoboyle** [comment]
Can you please provide more information on what the error was?

**Comment by austinoboyle** [comment]
Closing for lack of response. Feel free to re-open if this is still a problem.
