### ISSUE TITLE
How to login into LinkedIn

### ISSUE THREAD

**Issue by manoj-nain** [austinoboyle/scrape-linkedin-selenium#75]
Is there anyway to login automatically? Trying it manually but page closes before I can type in. Also do we need residential IP to avoid blocking? If so how to use it with this scraper?

**Comment by aminesafi8** [comment]
I think that the script login automatically, and there is no need to use another IP, we used this script and we scraped more than 10,000 profiles without any issue, you just need to do some break between 2 profiles to simulate a human behaviour.

**Comment by manoj-nain** [comment]
Hi Amin, Thank for response. But its not working for me. As soon as I run this script it re directs me to login than to sign up than window closes. And only after 4- 5 such failed attempt LinkedIn starts showing captcha. Cant understand what I am doing wrong.

**Comment by aminesafi8** [comment]
Ah so maybe the script needs some rectification.

**Comment by manoj-nain** [comment]
Did you tried it recently? If possible can you share your python code please.

**Comment by aminesafi8** [comment]
The last time I used this script was the last year, I have the same code as the master branch.

**Comment by austinoboyle** [comment]
@manoj-nain  Did you follow the setup instructions? Did you use your LI_AT token as an environment variable/function argument? If using the LI_AT cookie is not possible for you, we also support username/password login using the Scraper.login method. https://github.com/austinoboyle/scrape-linkedin-selenium/blob/81bdcc88577d0e4df48c77c22cb12784a0fd3c71/scrape_linkedin/Scraper.py#L64

**Comment by branniganbackagain** [comment]
> @manoj-nain Did you follow the setup instructions? Did you use your LI_AT token as an environment variable/function argument? If using the LI_AT cookie is not possible for you, we also support username/password login using the Scraper.login method.
> 
> https://github.com/austinoboyle/scrape-linkedin-selenium/blob/81bdcc88577d0e4df48c77c22cb12784a0fd3c71/scrape_linkedin/Scraper.py#L64

Just got into this. How are you using li_at to login? I'm using driver.add_cookie(), but when I hit sign in, it takes me to the login page and shows me my email

**Comment by austinoboyle** [comment]
@branniganbackagain Why are you using driver.add_cookie() manually? It should either be passed into the Scraper constructor directly (https://github.com/austinoboyle/scrape-linkedin-selenium/blob/81bdcc88577d0e4df48c77c22cb12784a0fd3c71/scrape_linkedin/Scraper.py#L25), or set as the `LI_AT` environment variable.

**Comment by austinoboyle** [comment]
Closing for lack of response. Feel free to re-open if this is still a problem.
