### ISSUE TITLE
Scrape company

### ISSUE THREAD

**Issue by Benhoro** [austinoboyle/scrape-linkedin-selenium#77]
Hi, I got this error when i try to scrape a company which does not have an overview content:

ipython-input-300-ffb910107714> in <module>
     10     # Get each company's overview, add to company_data list
     11     for name in my_company_list:
---> 12         overview = scraper.scrape(company=name).overview;
     13         overview['company_name'] = name
     14         company_data.append(overview)

~\anaconda3\lib\site-packages\scrape_linkedin\Company.py in overview(self)
     33         overview = {}
     34         overview['description'] = container.select_one(
---> 35             'section > p').get_text().strip()
     36 
     37         metadata_keys = container.select('.org-page-details__definition-term')

AttributeError: 'NoneType' object has no attribute 'get_text'

**Comment by austinoboyle** [comment]
Duplicate of #78

**Comment by ghilenasma** [comment]
please if someone have any updates about the 'nontype' error let me know
