### ISSUE TITLE
How do you run the tests?

### ISSUE THREAD

**Issue by jlopezvi** [austinoboyle/scrape-linkedin-selenium#8]
Hello,

I am not used to tests or any test framework. Is there a special command to run the tests ?
I am getting error running directly with python

$ python Profile_test.py
  File "Profile_test.py", line 10
    global profile_html
    ^
SyntaxError: name 'profile_html' is assigned to before global declaration

**Comment by austinoboyle** [comment]
You run the tests with pytest.  To install pytest, run `pip install pytest` 

The tests are pretty brittle right now, but if you would like to run them, you will want to follow these steps to set up a development environment.

1. (optional but highly recommended) Set up and start a virtual environment for the project (using virtualenv or similar)
2. Clone the repository, and run `$ pip install --editable .` from within the project folder
3. Run `$ pytest` from the project root to run the tests
