### ISSUE TITLE
dockerized version

### ISSUE THREAD

**Issue by x0rzkov** [austinoboyle/scrape-linkedin-selenium#80]
Hi,

Hope you are all well !

Is it possible to provide a dockerized version with a compose for scrape-linkedin-selenium+selenium ?

Cheers,
X

**Comment by obar1** [comment]
? you have to get a docker with python 3 and run 1 line ...

**Comment by austinoboyle** [comment]
This is not something I'm going to work on, as @obar1 mentions this should be a very simple install on a barebones VM. You just need python and a single pip install command
