### ISSUE TITLE
Support Recommendation Scraping

### ISSUE THREAD

**Issue by zzzzzzzzzzzzz** [austinoboyle/scrape-linkedin-selenium#82]
Hi!
Great tool! 
I was surprised that there are no reviews (for profiles) parsing. Are there any technical issues preventing this feature release? If not, I'd try to implement this and create pull request.

**Comment by zzzzzzzzzzzzz** [comment]
Reviews => Recommendations

**Comment by austinoboyle** [comment]
There don't appear to be any technical issues with that, and I'm definitely open to a pull request :)

**Comment by zzzzzzzzzzzzz** [comment]
@austinoboyle  would you be so kind to help me with a pull request creation? I created a local branch called "add-recommendations" and found unable to create the pull request (push branch) (Access denied).

**Comment by austinoboyle** [comment]
Full documentation is here, but the steps would look like:

1. Fork my repository so you have a copy (zzzzzzzzzzzzz/scrape-linkedin-selenium)
2. Create a branch off of that repository
3. Add your changes and commit/push the branch to your forked version
4. Go to my repo (austinoboyle/scrape-linkedin-selenium), and create the pull request. Use 'development' as the base branch, and your remote branch as the 'compare' branch.
5. Submit the pull request

**Comment by zzzzzzzzzzzzz** [comment]
Pull request is available here:)
https://github.com/austinoboyle/scrape-linkedin-selenium/pull/84
