### ISSUE TITLE
HTTP ERROR 429

### ISSUE THREAD

**Issue by anntdiv** [austinoboyle/scrape-linkedin-selenium#85]
The script sometime work, sometime it failed with error "InvalidCookieDomainException: Message: invalid cookie domain
  (Session info: chrome=86.0.4240.198)", while the script is running the popup browser show error "HTTP ERROR 429"

**Comment by austinoboyle** [comment]
How are you using this tool? Via the `scrapeli` CLI? Using the Python library in your own custom code? Do you have any screenshots? I wasn't able to reproduce this.

**Comment by austinoboyle** [comment]
Closing for lack of response. Feel free to re-open if this is still a problem.
