### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 80

### ISSUE THREAD

**Issue by xumengyan01** [austinoboyle/scrape-linkedin-selenium#86]
Hi, I tried to use `ProfileScraper` but kept getting the message
```
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 80
```
Is there any way for me not to downgrade my Chrome version and modify the driver? Thanks

**Comment by austinoboyle** [comment]
1. visit chrome://version to figure out which chrome version you are using
2. visit https://chromedriver.chromium.org/downloads
Scroll down and find a version that supports your chrome version, download it, replace the existing chromedriver you have with the new download.
