### ISSUE TITLE
headless and path to chromedriver

### ISSUE THREAD

**Issue by hosam00** [austinoboyle/scrape-linkedin-selenium#87]
how to make chrome driver headless?
how to pass the chrome driver path?

**Comment by austinoboyle** [comment]
1. Using the CLI, use the `--headless` flag.  Example: `scrapeli -u austinoboyle --headless`. Using the Python library, this is the default behaviour.
2. There is currently no option to 'pass' the path to Chromedriver to the CLI or Scraper class. The executable just needs to be in the PATH environment variable. Instructions to do this are in the README
