### ISSUE TITLE
Redundant method?

### ISSUE THREAD

**Issue by Kaan191** [austinoboyle/scrape-linkedin-selenium#88]
Quick question / observation, not an issue: I might be wrong, also... 

Is the get_html method in Scraper.py (lines 73-75) redundant? I don’t see it being called in any of the derived Scrapers eg CompanyScraper and ProfileScraper. They have their own get_xxx methods to capture html snippets, I note. Maybe it serves some other purpose that’s beyond me, or simply as a placeholder/reminder?

cheers
Kaan

**Comment by austinoboyle** [comment]
Yes, that is a bit out of date. It should probably become a method that just returns the full page html. As you noticed, this isn't used in any of the prebuilt routines of this utility, but could be useful to someone who is building custom functionality on top of these classes.
