### ISSUE TITLE
Profile Scraper Failing to Scroll Down

### ISSUE THREAD

**Issue by hp2500** [austinoboyle/scrape-linkedin-selenium#89]
Hi there, 

I am currently using the profile scraper and it worked well up until a few days ago on two different machines. However, since then all calls have been failing, because chromedriver fails to scroll down and I get the typical error message. 

Took too long to load profile.  Common problems/solutions:
                1. Invalid LI_AT value: ensure that yours is correct (they
                   update frequently)
                2. Slow Internet: increase the time out parameter in the Scraper
                   constructor
                3. Invalid e-mail address (or user does not allow e-mail scrapes) on scrape_by_email call

The scraper still navigates to the correct profiles, but since it doesn't scroll to the bottom of the page no information can be retrieved. Is there an easy fix for this? Maybe something changed about the linkedin page structure? Guidance would be much appreciated.

**Comment by senihucar** [comment]
try timeout

**Comment by senihucar** [comment]
TRY :
timeout {float}: default time to wait for async content to load
    default: 10

**Comment by senihucar** [comment]
Try to increase timeout..

timeout {float}: default time to wait for async content to load
    default: 10

**Comment by vmesel** [comment]
@senihucar this is not a timeout error, the scraper isn't scrolling down at all!

Increased mine to 1000s and same error around here.

**Comment by hp2500** [comment]
I can confirm this. I tried different parameter configurations on different computers and with different internet connections. The scraper still fails to scroll down.

**Comment by aabid-konverge** [comment]
Facing the same issue.The scraper is not able to retrieve any of the profile data.I don't know the exact cause but there might be some changes in css classes/selector in linkedin website.

**Comment by aabid-konverge** [comment]
The solution for above issue is to change the MAIN_SELECTOR class in ProfileScraper.py on linke no. 19 from
MAIN_SELECTOR = '.core-rail' to MAIN_SELECTOR = '.scaffold-layout__main'

**Comment by hp2500** [comment]
@aabid-konverge 
First of all, thanks! It seems like the CSS selector has been replaced. I adjusted the code, but I still run into the same issue. 

Did it fix the issue for you @vmesel?

**Comment by senihucar** [comment]
> @aabid-konverge
> First of all, thanks! It seems like the CSS selector has been replaced. I adjusted the code, but I still run into the same issue.
> 
> Did it fix the issue for you @vmesel?

profile scraper works smoothly after the update. If you setup with Anaconda please check the file directory and update .py files.  Company scrapers still not working.

**Comment by austinoboyle** [comment]
I merged a PR into master that should fix the issue for ProfileScraper, so the live version should work for profiles now. I have yet to look into the CompanyScraper, but I suspect the fix should be quite similar, if not identical.

**Comment by austinoboyle** [comment]
Actually, it looks like the Company page structure has changed fairly substantially away from what the Scraper currently supports. Filing a new issue for that. I won't have much time to work on it, but pull requests are always very welcome.
