### ISSUE TITLE
issue with setup file 

### ISSUE THREAD

**Issue by ghilenasma** [austinoboyle/scrape-linkedin-selenium#91]
Hello , 
I hope that you are doing well ; I found your contact Mail in the setup file I want to express my love for your work, you are awesome man 
can I ask for something !   would you please check with me some dependencies i can't execute the project in pycharm I am using pycharm and python 3.7  I copied thé LI_AT , defined the path to my chromedriver but steel doesn't work :(
kind regards

**Comment by austinoboyle** [comment]
Hi, I'm glad you like the work. I cannot help you with the amount of information provided here, please add specific details (commands run, logs, error messages, etc) if you would like me (or others) to try and help.

https://stackoverflow.com/help/how-to-ask
https://betterprogramming.pub/4-ways-to-ask-better-questions-as-a-software-engineer-a342ffc251a1

**Comment by austinoboyle** [comment]
Closing for lack of response, feel free to re-open if this is still a problem.
