### ISSUE TITLE
personal_info gives empty columns and wrong columns

### ISSUE THREAD

**Issue by Lunfer** [austinoboyle/scrape-linkedin-selenium#94]
While running a profilescraper_to_csv.py file, looking somehow like the example for companies, profile.personal_info when being printed as a csv shows in the name and the location column the number of connections, and the rest are empty. Only the image column has a URL. 
Also, if I try to print it to_dict it says that there is no such thing as a to_dict on scrape_linkedin.

**Comment by austinoboyle** [comment]
This description is not sufficient to debug the issue. Can you please add more details? This should include:
- What you are trying to achieve
- The output you expect
- The output you get

This should include:
- 1+ sample profile URLs where you see this issue
- Code snippets for how you are using the provided APIs
- Any error messages/logs

**Comment by Lunfer** [comment]
So here's the code I was trying to run: 

from scrape_linkedin import ProfileScraper 
import pandas as pd

users = ['zoikousteni','georgiosd']
user_skills = []
user_pinfo = []
with ProfileScraper(cookie='mycookie') as scraper:
    for name in users:
            pskills = scraper.scrape(user=name).skills
            pinfo= scraper.scrape(user=name).personal_info
            #profile['name'] = name        _<----note that this gives a typerror as well and that's why it's commented out_
            user_skills.append(pskills)
            user_pinfo.append(pinfo)
dfs = pd.DataFrame(user_skills)
dfs.to_csv('skills.csv', index=True)
dfi.to_csv('personal_info.csv', index=True)

Below I am attaching the csv files that I got after that so you can see for yourself:
[New folder.zip](https://github.com/austinoboyle/scrape-linkedin-selenium/files/6608253/New.folder.zip)

What I am trying to do is get some information about these two profiles so I can later continue with a personal project of mine to find some keywords. I am also attaching a photo of my terminal while the code is running: 
![1](https://user-images.githubusercontent.com/68249454/121006684-d60c8300-c799-11eb-9db0-b2655a0d276a.png)

And that is when trying to run the code tailored for the experiences part: 
![2](https://user-images.githubusercontent.com/68249454/121007077-4fa47100-c79a-11eb-973c-cf1f0244c8c4.png)

Also, when transposing the resulting csv 
![3](https://user-images.githubusercontent.com/68249454/121007712-cfcad680-c79a-11eb-9f05-8642db794402.png)
I get
![4](https://user-images.githubusercontent.com/68249454/121007742-d8231180-c79a-11eb-8515-aa9d8eb1cdd8.png)
and when I try to rename the columns with either the first two lines of code (which change absolutely nothing) (from the following image) or the last one it gives that result 
![7](https://user-images.githubusercontent.com/68249454/121008238-731beb80-c79b-11eb-9d04-48f2a21a59d4.png)

**Comment by austinoboyle** [comment]
Got it, I see two bugs from this, and my own testing based on this:
1.  there was a change in the "contact info" portion of LinkedIn
2. The company_href portion not working. I also have a better solution for this coming.

I can't really help you too much with the Pandas portion, but my guess is that this line is wrong:
  -`dfsT = pd.DataFrame(columns=["Zoi", "Giorgos"], data = dfsT)`

You could try this instead: `dfsT.rename(columns=users, inplace=True)`

**Comment by austinoboyle** [comment]
This should be fixed now, at least from a scrape_linkedin perspective.

**Comment by Lunfer** [comment]
Yeap you are right, had to re-run it a couple of times just to get the same results as you, even though I had the same version. Thank you for your help! :)
